msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2020-12-03 12:26+0000\n"
"Last-Translator: \n"
"Language-Team: Japanese\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.1\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Project-ID: 289505\n"
"X-Crowdin-Language: ja\n"
"X-Crowdin-File-ID: 688\n"
"Language: ja_JP\n"

#: redbot/cogs/audio/core/utilities/formatting.py:75
msgid "tracks"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:85
#: redbot/cogs/audio/core/utilities/formatting.py:274
msgid "Page {page_num}/{total_pages}"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:96
msgid "Connection to Lavalink has failed."
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:99
#: redbot/cogs/audio/core/utilities/player.py:596
#: redbot/cogs/audio/core/utilities/playlists.py:505
msgid "Please check your console or logs for details."
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:107
#: redbot/cogs/audio/core/utilities/playlists.py:535
msgid "Connect to a voice channel first."
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:110
#: redbot/cogs/audio/core/utilities/playlists.py:528
msgid "Connection to Lavalink has not yet been established."
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:116
msgid "Unable To Play Tracks"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:116
#: redbot/cogs/audio/core/utilities/player.py:444
#: redbot/cogs/audio/core/utilities/player.py:528
msgid "Queue size limit reached."
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:154
#: redbot/cogs/audio/core/utilities/player.py:604
msgid "Track Enqueued"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:169
#: redbot/cogs/audio/core/utilities/player.py:553
msgid "This track is not allowed in this server."
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:187
#: redbot/cogs/audio/core/utilities/player.py:575
msgid "Track exceeds maximum length."
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:204
#: redbot/cogs/audio/core/utilities/player.py:607
msgid "{time} until track playback: #{position} in queue"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:262
msgid "Tracks Found:"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:263
msgid "search results"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:265
msgid "Folders Found:"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:266
msgid "local folders"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:268
msgid "Files Found:"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:269
msgid "local tracks"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:381
#: redbot/cogs/audio/core/utilities/playlists.py:228
msgid "Unknown"
msgstr ""

#: redbot/cogs/audio/core/utilities/formatting.py:382
msgid " - Name:   <{pname}>\\n - Scope:  < {scope} >\\n - ID:     < {pid} >\\n - Tracks: < {ptracks} >\\n - Author: < {author} >\\n\\n"
msgstr ""

#: redbot/cogs/audio/core/utilities/local_tracks.py:108
#: redbot/cogs/audio/core/utilities/player.py:238
#: redbot/cogs/audio/core/utilities/player.py:248
#: redbot/cogs/audio/core/utilities/player.py:330
#: redbot/cogs/audio/core/utilities/player.py:655
msgid "Invalid Environment"
msgstr ""

#: redbot/cogs/audio/core/utilities/local_tracks.py:108
msgid "No localtracks folder."
msgstr ""

#: redbot/cogs/audio/core/utilities/miscellaneous.py:53
msgid "Not enough {currency}"
msgstr ""

#: redbot/cogs/audio/core/utilities/miscellaneous.py:54
msgid "{required_credits} {currency} required, but you have {bal}."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:78
msgid "music in {} servers"
msgstr "{} つのサーバーで再生中"

#: redbot/cogs/audio/core/utilities/player.py:136
#: redbot/cogs/audio/core/utilities/player.py:140
#: redbot/cogs/audio/core/utilities/player.py:145
msgid "There's nothing in the queue."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:142
msgid "Currently livestreaming {track}"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:147
msgid "{time} left on {track}"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:155
#: redbot/cogs/audio/core/utilities/player.py:190
msgid "Track Skipped"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:168
msgid "Track number must be equal to or greater than 1."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:174
msgid "There are only {queuelen} songs currently queued."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:180
msgid "{skip_to_track} Tracks Skipped"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:239
msgid "The owner needs to set the Spotify client ID and Spotify client secret, before Spotify URLs or codes can be used. \\nSee `{prefix}audioset spotifyapi` for instructions."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:249
msgid "The owner needs to set the YouTube API key before Spotify URLs or codes can be used.\\nSee `{prefix}audioset youtubeapi` for instructions."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:258
#: redbot/cogs/audio/core/utilities/player.py:367
#: redbot/cogs/audio/core/utilities/playlists.py:570
msgid "Unable To Get Tracks"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:259
#: redbot/cogs/audio/core/utilities/player.py:368
#: redbot/cogs/audio/core/utilities/playlists.py:571
msgid "Wait until the playlist has finished loading."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:270
#: redbot/cogs/audio/core/utilities/player.py:312
#: redbot/cogs/audio/core/utilities/player.py:410
#: redbot/cogs/audio/core/utilities/playlists.py:581
#: redbot/cogs/audio/core/utilities/playlists.py:614
msgid "Nothing found."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:273
#: redbot/cogs/audio/core/utilities/player.py:314
#: redbot/cogs/audio/core/utilities/player.py:425
#: redbot/cogs/audio/core/utilities/playlists.py:583
#: redbot/cogs/audio/core/utilities/playlists.py:616
msgid "Track is not playable."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:274
#: redbot/cogs/audio/core/utilities/player.py:315
#: redbot/cogs/audio/core/utilities/player.py:427
#: redbot/cogs/audio/core/utilities/playlists.py:584
#: redbot/cogs/audio/core/utilities/playlists.py:617
msgid "**{suffix}** is not a fully supported format and some tracks may not play."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:304
#: redbot/cogs/audio/core/utilities/player.py:395
#: redbot/cogs/audio/core/utilities/player.py:662
#: redbot/cogs/audio/core/utilities/playlists.py:413
#: redbot/cogs/audio/core/utilities/playlists.py:602
#: redbot/cogs/audio/core/utilities/playlists.py:631
msgid "Unable to Get Track"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:305
#: redbot/cogs/audio/core/utilities/player.py:396
#: redbot/cogs/audio/core/utilities/player.py:663
#: redbot/cogs/audio/core/utilities/playlists.py:414
#: redbot/cogs/audio/core/utilities/playlists.py:603
#: redbot/cogs/audio/core/utilities/playlists.py:632
msgid "I'm unable to get a track from Lavalink at the moment, try again in a few minutes."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:331
msgid "The Spotify API key or client secret has not been set properly. \\nUse `{prefix}audioset spotifyapi` for instructions."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:355
msgid "Unable To Find Tracks"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:356
msgid "This doesn't seem to be a supported Spotify URL or code."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:382
msgid "{query} is not an allowed query."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:418
msgid "Local tracks will not work if the `Lavalink.jar` cannot see the track.\\nThis may be due to permissions or because Lavalink.jar is being run in a different machine than the local tracks."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:491
msgid " {bad_tracks} tracks cannot be queued."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:497
msgid "No Title"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:503
msgid "Playlist Enqueued"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:506
msgid "Added {num} tracks to the queue.{maxlength_msg}"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:512
msgid "{time} until start of playlist playback: starts at #{position} in queue"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:593
msgid "Nothing found"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:628
msgid "Please wait, finding tracks..."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:634
msgid "Getting track {num}/{total}..."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:635
msgid "Matching track {num}/{total}..."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:636
#: redbot/cogs/audio/core/utilities/playlists.py:329
#: redbot/cogs/audio/core/utilities/playlists.py:402
msgid "Loading track {num}/{total}..."
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:637
msgid "Approximate time remaining: {seconds}"
msgstr ""

#: redbot/cogs/audio/core/utilities/player.py:672
msgid "The connection was reset while loading the playlist."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:71
msgid "You do not have the permissions to manage {name} (`{id}`) [**{scope}**]."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:89
msgid "You do not have the permissions to manage that playlist in {guild}."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:96
msgid "You do not have the permissions to manage playlist owned by {user}."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:100
msgid "You do not have the permissions to manage playlists in {scope} scope."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:104
msgid "No access to playlist."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:212
msgid "{match_count} playlists match {original_input}: Please try to be more specific, or use the playlist ID."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:229
msgid "{number}.    <{playlist.name}>\\n - Scope:  < {scope} >\\n - ID:     < {playlist.id} >\\n - Tracks: < {tracks} >\\n - Author: < {author} >\\n\\n"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:246
msgid "{playlists} playlists found, which one would you like?"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:265
#: redbot/cogs/audio/core/utilities/playlists.py:271
msgid "Too many matches found and you did not select which one you wanted."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:296
msgid "Playlists you can access in this server:"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:302
msgid "Playlists for {scope}:"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:306
msgid "Page {page_num}/{total_pages} | {num} playlists."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:322
#: redbot/cogs/audio/core/utilities/playlists.py:400
msgid "Please wait, adding tracks..."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:349
#: redbot/cogs/audio/core/utilities/playlists.py:452
msgid "Empty playlist {name} (`{id}`) [**{scope}**] created."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:354
#: redbot/cogs/audio/core/utilities/playlists.py:457
msgid "Added {num} tracks from the {playlist_name} playlist. {num_bad} track(s) could not be loaded."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:359
#: redbot/cogs/audio/core/utilities/playlists.py:462
msgid "Added {num} tracks from the {playlist_name} playlist."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:363
#: redbot/cogs/audio/core/utilities/playlists.py:466
msgid "Playlist Saved"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:502
msgid "Connection to Lavalink has failed"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:516
#: redbot/cogs/audio/core/utilities/playlists.py:527
#: redbot/cogs/audio/core/utilities/playlists.py:534
#: redbot/cogs/audio/core/utilities/playlists.py:547
msgid "Unable To Get Playlists"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:517
msgid "I don't have permission to connect to your channel."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:548
msgid "You must be in the voice channel to use the playlist command."
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:657
msgid "the Global"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:657
msgid "Global"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:659
msgid "the Server"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:659
msgid "Server"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:661
msgid "the User"
msgstr ""

#: redbot/cogs/audio/core/utilities/playlists.py:661
msgid "User"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:40
msgid "__Too many songs in the queue, only showing the first 500__.\\n\\n"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:57
msgid "**Currently livestreaming:**\\n"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:59
#: redbot/cogs/audio/core/utilities/queue.py:64
msgid "Requested by: **{user}**"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:62
msgid "Playing: "
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:76
msgid "requested by **{user}**\\n"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:80
msgid "Queue for __{guild_name}__"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:88
msgid "Page {page_num}/{total_pages} | {num_tracks} tracks, {num_remaining} remaining\\n"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:97
msgid "Auto-Play"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:103
msgid "Shuffle"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:109
msgid "Repeat"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:161
msgid "Matching Tracks:"
msgstr ""

#: redbot/cogs/audio/core/utilities/queue.py:164
msgid "Page {page_num}/{total_pages} | {num_tracks} tracks"
msgstr ""

